export type SoftwareStatus =
  | "not_installed"
  | "installed"
  | "update_available"
  | "installing"
  | "updating";

export type SoftwareVersion = {
  version: string;
  releaseDate: string;
  changelog: string;
  isCurrent?: boolean;
  isRecommended?: boolean;
};

export type Software = {
  id: string;
  name: string;
  icon: string;
  category: string;
  shortDescription: string;
  longDescription: string;
  publisher: string;
  sourceUrl: string;
  status: SoftwareStatus;
  installedVersion?: string;
  latestVersion: string;
  installedAt?: string;
  resources: { cpu: string; ram: string; disk: string };
  tags: string[];
  versions: SoftwareVersion[];
};

const v = (
  version: string,
  releaseDate: string,
  changelog: string,
  extra: Partial<SoftwareVersion> = {},
): SoftwareVersion => ({ version, releaseDate, changelog, ...extra });

export const CATEGORIES = [
  "Databases",
  "Media Servers",
  "Networking",
  "Monitoring",
  "Dev Tools",
  "Productivity",
] as const;

export const SEED_SOFTWARE: Software[] = [
  {
    id: "postgres",
    name: "PostgreSQL",
    icon: "🐘",
    category: "Databases",
    shortDescription: "Powerful open-source object-relational database system.",
    longDescription:
      "PostgreSQL is a proven, enterprise-class relational database with strong reputation for reliability, feature robustness, and performance.",
    publisher: "PostgreSQL Global Dev Group",
    sourceUrl: "https://www.postgresql.org",
    status: "installed",
    installedVersion: "16.1",
    latestVersion: "16.4",
    installedAt: "2025-03-14",
    resources: { cpu: "1 vCPU", ram: "512 MB", disk: "2 GB" },
    tags: ["sql", "relational", "acid"],
    versions: [
      v("16.4", "2026-06-12", "Security fixes, planner improvements.", { isRecommended: true }),
      v("16.2", "2026-02-08", "Bug fixes for logical replication."),
      v("16.1", "2025-11-09", "Minor patch release.", { isCurrent: true }),
      v("16.0", "2025-09-14", "Major release: parallel queries, JSON improvements."),
    ],
  },
  {
    id: "mysql",
    name: "MySQL",
    icon: "🐬",
    category: "Databases",
    shortDescription: "The world's most popular open-source database.",
    longDescription:
      "MySQL is a fast, reliable, scalable, and easy-to-use open-source relational database system.",
    publisher: "Oracle",
    sourceUrl: "https://www.mysql.com",
    status: "not_installed",
    latestVersion: "8.4.2",
    resources: { cpu: "1 vCPU", ram: "512 MB", disk: "1.5 GB" },
    tags: ["sql", "relational"],
    versions: [
      v("8.4.2", "2026-05-01", "LTS security patches.", { isRecommended: true }),
      v("8.4.0", "2026-04-30", "New LTS baseline."),
      v("8.0.36", "2025-12-15", "Legacy branch."),
    ],
  },
  {
    id: "redis",
    name: "Redis",
    icon: "🟥",
    category: "Databases",
    shortDescription: "In-memory data structure store used as cache and broker.",
    longDescription: "Redis is an open-source, in-memory data store, used as a database, cache, streaming engine, and message broker.",
    publisher: "Redis Ltd.",
    sourceUrl: "https://redis.io",
    status: "update_available",
    installedVersion: "7.2.3",
    latestVersion: "7.4.1",
    installedAt: "2025-06-20",
    resources: { cpu: "0.5 vCPU", ram: "256 MB", disk: "200 MB" },
    tags: ["cache", "kv"],
    versions: [
      v("7.4.1", "2026-06-01", "Vector similarity search improvements.", { isRecommended: true }),
      v("7.4.0", "2026-05-10", "Vector search, hash field TTL."),
      v("7.2.3", "2025-05-11", "Security patches.", { isCurrent: true }),
    ],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    icon: "🍃",
    category: "Databases",
    shortDescription: "Document-oriented NoSQL database.",
    longDescription: "MongoDB is a source-available cross-platform document-oriented database program.",
    publisher: "MongoDB Inc.",
    sourceUrl: "https://www.mongodb.com",
    status: "not_installed",
    latestVersion: "7.0.11",
    resources: { cpu: "1 vCPU", ram: "1 GB", disk: "2 GB" },
    tags: ["nosql", "document"],
    versions: [
      v("7.0.11", "2026-06-20", "Storage engine fixes.", { isRecommended: true }),
      v("7.0.5", "2026-01-18", "Bug fixes."),
    ],
  },
  {
    id: "plex",
    name: "Plex Media Server",
    icon: "🎬",
    category: "Media Servers",
    shortDescription: "Stream your movies, shows and music anywhere.",
    longDescription: "Plex organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices.",
    publisher: "Plex Inc.",
    sourceUrl: "https://www.plex.tv",
    status: "installed",
    installedVersion: "1.40.2",
    latestVersion: "1.40.2",
    installedAt: "2025-01-10",
    resources: { cpu: "2 vCPU", ram: "1 GB", disk: "500 MB" },
    tags: ["media", "streaming"],
    versions: [
      v("1.40.2", "2026-06-18", "HDR tone mapping improvements.", { isCurrent: true, isRecommended: true }),
      v("1.40.1", "2026-05-02", "Bug fixes."),
    ],
  },
  {
    id: "jellyfin",
    name: "Jellyfin",
    icon: "🪼",
    category: "Media Servers",
    shortDescription: "The Free Software Media System.",
    longDescription: "Jellyfin is a free software media system that puts you in control of managing and streaming your media.",
    publisher: "Jellyfin Project",
    sourceUrl: "https://jellyfin.org",
    status: "update_available",
    installedVersion: "10.9.6",
    latestVersion: "10.10.0",
    installedAt: "2025-04-22",
    resources: { cpu: "2 vCPU", ram: "1 GB", disk: "400 MB" },
    tags: ["media", "opensource"],
    versions: [
      v("10.10.0", "2026-07-01", "New trickplay engine, subtitle improvements.", { isRecommended: true }),
      v("10.9.11", "2026-04-15", "Security fixes."),
      v("10.9.6", "2026-02-10", "Stability patch.", { isCurrent: true }),
    ],
  },
  {
    id: "sonarr",
    name: "Sonarr",
    icon: "📺",
    category: "Media Servers",
    shortDescription: "Smart PVR for newsgroup and bittorrent users.",
    longDescription: "Sonarr is a PVR for Usenet and BitTorrent that can monitor RSS feeds for new episodes and grab, sort and rename them.",
    publisher: "Sonarr Team",
    sourceUrl: "https://sonarr.tv",
    status: "not_installed",
    latestVersion: "4.0.9",
    resources: { cpu: "0.5 vCPU", ram: "256 MB", disk: "150 MB" },
    tags: ["automation", "media"],
    versions: [
      v("4.0.9", "2026-06-05", "Bug fixes.", { isRecommended: true }),
      v("4.0.8", "2026-05-01", "Indexer improvements."),
    ],
  },
  {
    id: "navidrome",
    name: "Navidrome",
    icon: "🎵",
    category: "Media Servers",
    shortDescription: "Modern music server compatible with Subsonic.",
    longDescription: "Navidrome is an open source web-based music collection server and streamer.",
    publisher: "Navidrome",
    sourceUrl: "https://www.navidrome.org",
    status: "not_installed",
    latestVersion: "0.52.5",
    resources: { cpu: "0.5 vCPU", ram: "256 MB", disk: "200 MB" },
    tags: ["music", "streaming"],
    versions: [v("0.52.5", "2026-06-11", "Bug fixes.", { isRecommended: true })],
  },
  {
    id: "pihole",
    name: "Pi-hole",
    icon: "🕳️",
    category: "Networking",
    shortDescription: "Network-wide ad blocking via DNS sinkhole.",
    longDescription: "Pi-hole is a Linux network-level advertisement and Internet tracker blocking application.",
    publisher: "Pi-hole LLC",
    sourceUrl: "https://pi-hole.net",
    status: "installed",
    installedVersion: "5.18.3",
    latestVersion: "5.18.3",
    installedAt: "2025-02-01",
    resources: { cpu: "0.25 vCPU", ram: "128 MB", disk: "100 MB" },
    tags: ["dns", "adblock"],
    versions: [
      v("5.18.3", "2026-06-01", "Query filtering fixes.", { isCurrent: true, isRecommended: true }),
    ],
  },
  {
    id: "wireguard",
    name: "WireGuard",
    icon: "🛡️",
    category: "Networking",
    shortDescription: "Fast, modern, secure VPN tunnel.",
    longDescription: "WireGuard is an extremely simple yet fast and modern VPN utilizing state-of-the-art cryptography.",
    publisher: "WireGuard LLC",
    sourceUrl: "https://www.wireguard.com",
    status: "update_available",
    installedVersion: "1.0.20220627",
    latestVersion: "1.0.20250515",
    installedAt: "2024-09-11",
    resources: { cpu: "0.25 vCPU", ram: "64 MB", disk: "20 MB" },
    tags: ["vpn", "security"],
    versions: [
      v("1.0.20250515", "2026-05-15", "Kernel module compatibility.", { isRecommended: true }),
      v("1.0.20220627", "2024-06-27", "Legacy version.", { isCurrent: true }),
    ],
  },
  {
    id: "nginx-proxy-manager",
    name: "Nginx Proxy Manager",
    icon: "🚦",
    category: "Networking",
    shortDescription: "Reverse proxy with a beautiful UI.",
    longDescription: "A Docker container for managing Nginx proxy hosts with a simple, powerful interface.",
    publisher: "NPM Community",
    sourceUrl: "https://nginxproxymanager.com",
    status: "not_installed",
    latestVersion: "2.11.3",
    resources: { cpu: "0.5 vCPU", ram: "256 MB", disk: "300 MB" },
    tags: ["proxy", "ssl"],
    versions: [v("2.11.3", "2026-05-22", "SSL renewal fixes.", { isRecommended: true })],
  },
  {
    id: "tailscale",
    name: "Tailscale",
    icon: "🧵",
    category: "Networking",
    shortDescription: "Zero-config VPN based on WireGuard.",
    longDescription: "Tailscale creates a secure network between your servers, computers, and cloud instances.",
    publisher: "Tailscale Inc.",
    sourceUrl: "https://tailscale.com",
    status: "not_installed",
    latestVersion: "1.68.2",
    resources: { cpu: "0.25 vCPU", ram: "128 MB", disk: "80 MB" },
    tags: ["vpn", "mesh"],
    versions: [v("1.68.2", "2026-06-25", "Exit node improvements.", { isRecommended: true })],
  },
  {
    id: "grafana",
    name: "Grafana",
    icon: "📊",
    category: "Monitoring",
    shortDescription: "Query, visualize and alert on metrics.",
    longDescription: "Grafana is the open source analytics & monitoring solution for every database.",
    publisher: "Grafana Labs",
    sourceUrl: "https://grafana.com",
    status: "installed",
    installedVersion: "11.1.0",
    latestVersion: "11.1.0",
    installedAt: "2025-05-05",
    resources: { cpu: "1 vCPU", ram: "512 MB", disk: "300 MB" },
    tags: ["dashboards", "metrics"],
    versions: [
      v("11.1.0", "2026-06-15", "New scenes panel, alerting UX.", { isCurrent: true, isRecommended: true }),
    ],
  },
  {
    id: "prometheus",
    name: "Prometheus",
    icon: "🔥",
    category: "Monitoring",
    shortDescription: "Open-source systems monitoring & alerting.",
    longDescription: "Prometheus is an open-source systems monitoring and alerting toolkit originally built at SoundCloud.",
    publisher: "Prometheus Authors",
    sourceUrl: "https://prometheus.io",
    status: "update_available",
    installedVersion: "2.51.2",
    latestVersion: "2.53.0",
    installedAt: "2025-05-05",
    resources: { cpu: "1 vCPU", ram: "1 GB", disk: "5 GB" },
    tags: ["metrics", "tsdb"],
    versions: [
      v("2.53.0", "2026-06-20", "OTLP receiver stability.", { isRecommended: true }),
      v("2.52.0", "2026-05-05", "Native histograms GA."),
      v("2.51.2", "2026-04-10", "Bug fixes.", { isCurrent: true }),
    ],
  },
  {
    id: "uptime-kuma",
    name: "Uptime Kuma",
    icon: "🟢",
    category: "Monitoring",
    shortDescription: "Fancy self-hosted monitoring tool.",
    longDescription: "Uptime Kuma is an easy-to-use self-hosted monitoring tool.",
    publisher: "Louis Lam",
    sourceUrl: "https://uptime.kuma.pet",
    status: "not_installed",
    latestVersion: "1.23.13",
    resources: { cpu: "0.25 vCPU", ram: "128 MB", disk: "100 MB" },
    tags: ["uptime", "alerts"],
    versions: [v("1.23.13", "2026-06-08", "Notification fixes.", { isRecommended: true })],
  },
  {
    id: "netdata",
    name: "Netdata",
    icon: "📈",
    category: "Monitoring",
    shortDescription: "Real-time performance monitoring.",
    longDescription: "Netdata is distributed, real-time, performance and health monitoring for systems and applications.",
    publisher: "Netdata Inc.",
    sourceUrl: "https://www.netdata.cloud",
    status: "not_installed",
    latestVersion: "1.46.3",
    resources: { cpu: "0.5 vCPU", ram: "256 MB", disk: "200 MB" },
    tags: ["metrics", "realtime"],
    versions: [v("1.46.3", "2026-06-12", "Agent fixes.", { isRecommended: true })],
  },
  {
    id: "gitea",
    name: "Gitea",
    icon: "🍵",
    category: "Dev Tools",
    shortDescription: "Self-hosted Git service written in Go.",
    longDescription: "Gitea is a painless, self-hosted, all-in-one software development service.",
    publisher: "Gitea Ltd.",
    sourceUrl: "https://gitea.io",
    status: "installed",
    installedVersion: "1.22.0",
    latestVersion: "1.22.1",
    installedAt: "2025-06-01",
    resources: { cpu: "0.5 vCPU", ram: "512 MB", disk: "1 GB" },
    tags: ["git", "vcs"],
    versions: [
      v("1.22.1", "2026-06-30", "Security patch.", { isRecommended: true }),
      v("1.22.0", "2026-05-25", "Actions GA.", { isCurrent: true }),
    ],
  },
  {
    id: "code-server",
    name: "code-server",
    icon: "💻",
    category: "Dev Tools",
    shortDescription: "Run VS Code on any machine anywhere.",
    longDescription: "code-server lets you run VS Code on a remote server, accessible through the browser.",
    publisher: "Coder",
    sourceUrl: "https://coder.com",
    status: "not_installed",
    latestVersion: "4.90.3",
    resources: { cpu: "1 vCPU", ram: "1 GB", disk: "500 MB" },
    tags: ["ide", "remote"],
    versions: [v("4.90.3", "2026-06-14", "Extension compatibility.", { isRecommended: true })],
  },
  {
    id: "portainer",
    name: "Portainer",
    icon: "🐳",
    category: "Dev Tools",
    shortDescription: "Container management made easy.",
    longDescription: "Portainer is a lightweight service delivery platform for containerized applications.",
    publisher: "Portainer.io",
    sourceUrl: "https://www.portainer.io",
    status: "update_available",
    installedVersion: "2.19.4",
    latestVersion: "2.20.3",
    installedAt: "2025-02-14",
    resources: { cpu: "0.5 vCPU", ram: "256 MB", disk: "300 MB" },
    tags: ["docker", "containers"],
    versions: [
      v("2.20.3", "2026-06-19", "Kubernetes UI improvements.", { isRecommended: true }),
      v("2.19.4", "2026-02-10", "Bug fixes.", { isCurrent: true }),
    ],
  },
  {
    id: "n8n",
    name: "n8n",
    icon: "🔗",
    category: "Dev Tools",
    shortDescription: "Workflow automation for technical people.",
    longDescription: "n8n is an extendable workflow automation tool with a fair-code license.",
    publisher: "n8n GmbH",
    sourceUrl: "https://n8n.io",
    status: "not_installed",
    latestVersion: "1.49.0",
    resources: { cpu: "1 vCPU", ram: "512 MB", disk: "400 MB" },
    tags: ["automation", "workflow"],
    versions: [v("1.49.0", "2026-06-26", "New nodes and fixes.", { isRecommended: true })],
  },
  {
    id: "nextcloud",
    name: "Nextcloud",
    icon: "☁️",
    category: "Productivity",
    shortDescription: "Self-hosted productivity platform.",
    longDescription: "Nextcloud offers on-premises file sync and share, communication, groupware, and more.",
    publisher: "Nextcloud GmbH",
    sourceUrl: "https://nextcloud.com",
    status: "installed",
    installedVersion: "29.0.3",
    latestVersion: "29.0.3",
    installedAt: "2024-12-18",
    resources: { cpu: "1 vCPU", ram: "1 GB", disk: "3 GB" },
    tags: ["files", "collab"],
    versions: [
      v("29.0.3", "2026-06-06", "Hub 8 fixes.", { isCurrent: true, isRecommended: true }),
    ],
  },
  {
    id: "vaultwarden",
    name: "Vaultwarden",
    icon: "🔐",
    category: "Productivity",
    shortDescription: "Unofficial Bitwarden-compatible server.",
    longDescription: "Vaultwarden is an alternative implementation of the Bitwarden server API written in Rust.",
    publisher: "Vaultwarden",
    sourceUrl: "https://github.com/dani-garcia/vaultwarden",
    status: "update_available",
    installedVersion: "1.30.5",
    latestVersion: "1.32.0",
    installedAt: "2025-01-30",
    resources: { cpu: "0.25 vCPU", ram: "128 MB", disk: "100 MB" },
    tags: ["passwords", "security"],
    versions: [
      v("1.32.0", "2026-06-22", "WebAuthn 2FA fixes.", { isRecommended: true }),
      v("1.31.0", "2026-04-01", "Passkey support."),
      v("1.30.5", "2026-01-25", "Patch release.", { isCurrent: true }),
    ],
  },
  {
    id: "paperless-ngx",
    name: "Paperless-ngx",
    icon: "📄",
    category: "Productivity",
    shortDescription: "Index and archive scanned documents.",
    longDescription: "Paperless-ngx is a community-supported supercharged version of paperless: scan, index and archive your documents.",
    publisher: "Paperless-ngx Team",
    sourceUrl: "https://docs.paperless-ngx.com",
    status: "not_installed",
    latestVersion: "2.11.1",
    resources: { cpu: "0.5 vCPU", ram: "512 MB", disk: "1 GB" },
    tags: ["docs", "ocr"],
    versions: [v("2.11.1", "2026-06-17", "OCR pipeline improvements.", { isRecommended: true })],
  },
  {
    id: "immich",
    name: "Immich",
    icon: "🖼️",
    category: "Productivity",
    shortDescription: "Self-hosted photo & video backup.",
    longDescription: "Immich is a high performance self-hosted photo and video backup solution.",
    publisher: "Immich Team",
    sourceUrl: "https://immich.app",
    status: "not_installed",
    latestVersion: "1.108.0",
    resources: { cpu: "2 vCPU", ram: "2 GB", disk: "5 GB" },
    tags: ["photos", "backup"],
    versions: [v("1.108.0", "2026-06-28", "ML improvements.", { isRecommended: true })],
  },
];
