package navigations

import "github.com/izetmolla/containerws/models"

// BuiltIn returns the static workspace menu. Always available regardless of
// containers / DB navigation rows.
func BuiltIn() []models.Navigation {
	return []models.Navigation{
		{
			ID:       "builtin-workspace",
			Title:    "Workspace",
			OrderNr:  0,
			IsActive: true,
			Children: []models.Navigation{
				{
					ID:       "builtin-dashboard",
					Title:    "Dashboard",
					To:       "/",
					Icon:     "LayoutDashboard",
					OrderNr:  1,
					IsActive: true,
				},
				{
					ID:       "builtin-softwares",
					Title:    "Softwares",
					To:       "/softwares",
					Icon:     "Package",
					OrderNr:  2,
					IsActive: true,
				},
				{
					ID:       "builtin-brew",
					Title:    "Brew Manager",
					To:       "/brew",
					Icon:     "CupSoda",
					OrderNr:  3,
					IsActive: true,
				},
				{
					ID:       "builtin-users",
					Title:    "Users",
					To:       "/users",
					Icon:     "Users",
					OrderNr:  4,
					IsActive: true,
				},
				{
					ID:       "builtin-vscode",
					Title:    "VS Code",
					To:       "/vscode",
					Icon:     "Code",
					OrderNr:  5,
					IsActive: true,
				},
				{
					ID:       "builtin-filemanager",
					Title:    "Files",
					To:       "/filemanager",
					Icon:     "FolderOpen",
					OrderNr:  6,
					IsActive: true,
				},
				{
					ID:       "builtin-kubernetes",
					Title:    "Kubernetes",
					To:       "/kubernetes",
					Icon:     "Hexagon",
					OrderNr:  7,
					IsActive: true,
					Children: []models.Navigation{
						{
							ID:       "builtin-k8s-group-cluster",
							Title:    "Cluster",
							Icon:     "Server",
							OrderNr:  1,
							IsActive: true,
							Children: []models.Navigation{
								{
									ID:       "builtin-k8s-cluster",
									Title:    "Overview",
									To:       "/kubernetes/cluster",
									Icon:     "Server",
									OrderNr:  1,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-nodes",
									Title:    "Nodes",
									To:       "/kubernetes/nodes",
									Icon:     "HardDrive",
									OrderNr:  2,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-namespaces",
									Title:    "Namespaces",
									To:       "/kubernetes/namespaces",
									Icon:     "FolderTree",
									OrderNr:  3,
									IsActive: true,
								},
							},
						},
						{
							ID:       "builtin-k8s-group-workloads",
							Title:    "Workloads",
							Icon:     "Layers",
							OrderNr:  2,
							IsActive: true,
							Children: []models.Navigation{
								{
									ID:       "builtin-k8s-pods",
									Title:    "Pods",
									To:       "/kubernetes/pods",
									Icon:     "Box",
									OrderNr:  1,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-deployments",
									Title:    "Deployments",
									To:       "/kubernetes/deployments",
									Icon:     "Layers",
									OrderNr:  2,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-statefulsets",
									Title:    "StatefulSets",
									To:       "/kubernetes/statefulsets",
									Icon:     "Database",
									OrderNr:  3,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-daemonsets",
									Title:    "DaemonSets",
									To:       "/kubernetes/daemonsets",
									Icon:     "Blocks",
									OrderNr:  4,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-jobs",
									Title:    "Jobs & CronJobs",
									To:       "/kubernetes/jobs",
									Icon:     "Timer",
									OrderNr:  5,
									IsActive: true,
								},
							},
						},
						{
							ID:       "builtin-k8s-group-network",
							Title:    "Network",
							Icon:     "Network",
							OrderNr:  3,
							IsActive: true,
							Children: []models.Navigation{
								{
									ID:       "builtin-k8s-services",
									Title:    "Services",
									To:       "/kubernetes/services",
									Icon:     "Network",
									OrderNr:  1,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-ingresses",
									Title:    "Ingresses",
									To:       "/kubernetes/ingresses",
									Icon:     "Globe",
									OrderNr:  2,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-network-policies",
									Title:    "NetworkPolicies",
									To:       "/kubernetes/network-policies",
									Icon:     "Shield",
									OrderNr:  3,
									IsActive: true,
								},
							},
						},
						{
							ID:       "builtin-k8s-group-config",
							Title:    "Config",
							Icon:     "FileCode",
							OrderNr:  4,
							IsActive: true,
							Children: []models.Navigation{
								{
									ID:       "builtin-k8s-configmaps",
									Title:    "ConfigMaps",
									To:       "/kubernetes/configmaps",
									Icon:     "FileCode",
									OrderNr:  1,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-secrets",
									Title:    "Secrets",
									To:       "/kubernetes/secrets",
									Icon:     "KeyRound",
									OrderNr:  2,
									IsActive: true,
								},
							},
						},
						{
							ID:       "builtin-k8s-group-storage",
							Title:    "Storage",
							Icon:     "HardDriveDownload",
							OrderNr:  5,
							IsActive: true,
							Children: []models.Navigation{
								{
									ID:       "builtin-k8s-pvcs",
									Title:    "PersistentVolumeClaims",
									To:       "/kubernetes/persistentvolumeclaims",
									Icon:     "HardDriveDownload",
									OrderNr:  1,
									IsActive: true,
								},
								{
									ID:       "builtin-k8s-storageclasses",
									Title:    "StorageClasses",
									To:       "/kubernetes/storageclasses",
									Icon:     "Database",
									OrderNr:  2,
									IsActive: true,
								},
							},
						},
						{
							ID:       "builtin-k8s-applications",
							Title:    "Applications",
							To:       "/kubernetes/applications",
							Icon:     "AppWindow",
							OrderNr:  6,
							IsActive: true,
						},
						{
							ID:       "builtin-k8s-settings",
							Title:    "Settings",
							To:       "/kubernetes/settings",
							Icon:     "Settings",
							OrderNr:  7,
							IsActive: true,
						},
					},
				},
				{
					ID:       "builtin-docker",
					Title:    "Docker",
					To:       "/docker",
					Icon:     "Box",
					OrderNr:  8,
					IsActive: true,
					Children: []models.Navigation{
						{
							ID:       "builtin-docker-containers",
							Title:    "Containers",
							To:       "/docker/containers",
							Icon:     "Container",
							OrderNr:  1,
							IsActive: true,
						},
						{
							ID:       "builtin-docker-images",
							Title:    "Images",
							To:       "/docker/images",
							Icon:     "HardDrive",
							OrderNr:  2,
							IsActive: true,
						},
						{
							ID:       "builtin-docker-networks",
							Title:    "Networks",
							To:       "/docker/networks",
							Icon:     "Network",
							OrderNr:  3,
							IsActive: true,
						},
						{
							ID:       "builtin-docker-volumes",
							Title:    "Volumes",
							To:       "/docker/volumes",
							Icon:     "Database",
							OrderNr:  4,
							IsActive: true,
						},
						{
							ID:       "builtin-docker-stacks",
							Title:    "Stacks",
							To:       "/docker/stacks",
							Icon:     "Layers",
							OrderNr:  5,
							IsActive: true,
						},
						{
							ID:       "builtin-docker-templates",
							Title:    "Templates",
							To:       "/docker/templates",
							Icon:     "LayoutTemplate",
							OrderNr:  6,
							IsActive: true,
						},
						{
							ID:       "builtin-docker-environments",
							Title:    "Environments",
							To:       "/docker/environments",
							Icon:     "Server",
							OrderNr:  7,
							IsActive: true,
						},
					},
				},
				{
					ID:       "builtin-proxymanager",
					Title:    "Proxy Manager",
					To:       "/proxymanager",
					Icon:     "Globe",
					OrderNr:  9,
					IsActive: true,
					Children: []models.Navigation{
						{
							ID:       "builtin-proxy-overview",
							Title:    "Settings",
							To:       "/proxymanager/overview",
							Icon:     "Settings",
							OrderNr:  1,
							IsActive: true,
						},
						{
							ID:       "builtin-proxy-hosts",
							Title:    "Hosts",
							To:       "/proxymanager/hosts",
							Icon:     "Server",
							OrderNr:  2,
							IsActive: true,
						},
						{
							ID:       "builtin-proxy-ssl",
							Title:    "SSL & Redirects",
							To:       "/proxymanager/ssl",
							Icon:     "Shield",
							OrderNr:  3,
							IsActive: true,
						},
						{
							ID:       "builtin-proxy-status",
							Title:    "Status",
							To:       "/proxymanager/status",
							Icon:     "Activity",
							OrderNr:  4,
							IsActive: true,
						},
						{
							ID:       "builtin-proxy-logs",
							Title:    "Logs",
							To:       "/proxymanager/logs",
							Icon:     "ScrollText",
							OrderNr:  5,
							IsActive: true,
						},
					},
				},
				{
					ID:       "builtin-settings",
					Title:    "Settings",
					Icon:     "Settings",
					OrderNr:  10,
					IsActive: true,
					Children: []models.Navigation{
						{
							ID:       "builtin-settings-general",
							Title:    "General",
							To:       "/settings",
							Icon:     "SlidersHorizontal",
							OrderNr:  1,
							IsActive: true,
						},
						{
							ID:       "builtin-settings-environments",
							Title:    "Environments",
							To:       "/settings/environments",
							Icon:     "Braces",
							OrderNr:  2,
							IsActive: true,
						},
						{
							ID:       "builtin-settings-options",
							Title:    "Options",
							To:       "/settings/options",
							Icon:     "Sliders",
							OrderNr:  3,
							IsActive: true,
						},
						{
							ID:       "builtin-settings-mcp",
							Title:    "MCP",
							To:       "/settings/mcp",
							Icon:     "KeyRound",
							OrderNr:  4,
							IsActive: true,
						},
						{
							ID:       "builtin-vnc-novnc",
							Title:    "Vnc & NoVnc",
							To:       "/vnc-novnc",
							Icon:     "Monitor",
							OrderNr:  5,
							IsActive: true,
						},
						{
							ID:       "builtin-settings-update",
							Title:    "Update",
							To:       "/settings/update",
							Icon:     "RefreshCw",
							OrderNr:  6,
							IsActive: true,
						},
					},
				},
			},
		},
	}
}
